version: '3.9'

services:
  psql:
    image: postgres:latest
    container_name: psql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin 
      POSTGRES_DB: dev
    volumes:
      - masterbom-db:/var/lib/postgresql/data
      - "./psql/initdb.sql:/docker-entrypoint-initdb.d/init.sql"

  api:
    container_name: api
    ports:
      - '5000:5000'
    build:
      context: ../../ 
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    environment:
      NODE_ENV: development
      PGHOST: psql
      PGUSER: admin 
      PGDATABASE: dev
      PGPORT: 5432
      SERVER_PORT: 5000
    depends_on:
      - psql

volumes:
  masterbom-db:
