version: '3.9'

services:
  postgresql:
    image: postgres:latest
    container_name: ${PGHOST} 
    ports:
      - '${PGPORT}:${PGPORT}'
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - masterbom-db:/var/lib/postgresql/data
      - "./psql/initdb.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - db
  masterbom-api:
    container_name: masterbom-api
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    # env file specification required due to build context
    env_file: 
      - .env
    build:
      context: ../ 
      dockerfile: docker/api/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    depends_on:
      - postgresql
    networks:
      - db

volumes:
  masterbom-db:

networks:
  db:
    driver: bridge
